import { useEffect, useState } from 'react';
import { supabase } from '../../lib/supabase';
import TransferenciasPicker from '../transferencias/TransferenciasPicker';
import { api, upload } from './api';
import { duration, fromGuion, scene, visualTypes } from './types';
import type { Asset, Guion, Job, Project, Scene } from './types';
import Preview from './Preview';
import './videolab.css';

const activeStates=['queued','preparing','rendering','finalizing'];
const labels:Record<string,string>={queued:'En cola',preparing:'Preparando',rendering:'Renderizando',finalizing:'Verificando MP4',completed:'Completado',failed:'Falló',cancelled:'Cancelado'};
function Numeric({label,value,onChange,min=0,max=60,step=1}:{label:string;value:number;onChange:(n:number)=>void;min?:number;max?:number;step?:number}) {
  return <label>{label}<input type="number" min={min} max={max} step={step} value={value} onChange={e=>{const n=Number(e.target.value);if(Number.isFinite(n))onChange(n);}}/></label>;
}
export default function VideoLabView() {
  const [guiones,setGuiones]=useState<Guion[]>([]),[projects,setProjects]=useState<Pick<Project,'id'|'name'>[]>([]);
  const [project,setProject]=useState<Project|null>(null),[assets,setAssets]=useState<Asset[]>([]),[music,setMusic]=useState<Asset[]>([]),[jobs,setJobs]=useState<Job[]>([]);
  const [error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[progress,setProgress]=useState(0),[dirty,setDirty]=useState(false);
  const [picker,setPicker]=useState<string|null>(null),[drag,setDrag]=useState<number|null>(null),[admin,setAdmin]=useState<Guion|null>(null),[sceneJson,setSceneJson]=useState('');
  const task=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');setNotice('');try{await fn();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);setProgress(0);}};
  const loadGuiones=async()=>{const {data,error}=await supabase.from('videolab_guiones').select('id,nombre,descripcion,objetivo,escenas,musica_sugerida,activo').order('nombre');if(error)throw error;setGuiones(data as Guion[]);};
  const reload=async()=>{const list=await api<Pick<Project,'id'|'name'>[]>('/projects');setProjects(list);setMusic(await api<Asset[]>('/music'));await loadGuiones();};
  useEffect(()=>{void task(reload);},[]);
  useEffect(()=>{if(!project)return;let stopped=false;const poll=async()=>{try{const result=await api<Job[]>(`/jobs?projectId=${project.id}`);if(!stopped)setJobs(result);}catch(e){if(!stopped)setError(e instanceof Error?e.message:'No se pudo consultar el render');}};void poll();const interval=setInterval(()=>void poll(),2500);return()=>{stopped=true;clearInterval(interval);};},[project?.id]);
  useEffect(()=>{const handler=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',handler);return()=>window.removeEventListener('beforeunload',handler);},[dirty]);
  function edit(next:Project){setProject(next);setDirty(true);try{sessionStorage.setItem('videolab-draft-'+next.id,JSON.stringify(next));}catch{setNotice('No se pudo conservar el borrador local. Guardá el proyecto antes de salir.');}}
  function updateScene(id:string,value:Partial<Scene>){if(project)edit({...project,scenes:project.scenes.map(s=>s.id===id?{...s,...value}:s)});}
  function reorder(from:number,to:number){if(!project||from===to)return;const scenes=[...project.scenes];scenes.splice(to,0,scenes.splice(from,1)[0]);scenes[scenes.length-1]={...scenes[scenes.length-1],transition:'cut',overlap:0};edit({...project,scenes});}
  async function open(id:string){const p=await api<Project>(`/projects/${id}`);setAssets(await api<Asset[]>(`/projects/${id}/assets`));let draft:Project|null=null;try{draft=JSON.parse(sessionStorage.getItem('videolab-draft-'+id)||'null');}catch{/* Draft storage is optional. */}const restore=draft?.revision===p.revision&&window.confirm('Hay cambios locales sin guardar. ¿Recuperarlos?');setProject(restore?draft:p);setDirty(Boolean(restore));setJobs([]);}
  async function save(){if(!project)throw new Error('Sin proyecto');const p=await api<Project>(`/projects/${project.id}`,'PUT',project);setProject(p);setDirty(false);try{sessionStorage.removeItem('videolab-draft-'+p.id);}catch{/* Server copy is authoritative. */}return p;}
  function assign(sid:string,a:Asset){setAssets(current=>[...current.filter(x=>x.id!==a.id),a]);if(project){const s=project.scenes.find(s=>s.id===sid)!;updateScene(sid,{assetId:a.id,inFrame:0,frames:a.kind==='video'?Math.max(1,Math.min(s.frames,Math.floor(a.probe.duration*30))):s.frames});}}
  async function importLocal(sid:string,file:File){if(!project)return;const a=await upload<Asset>(`/projects/${project.id}/assets`,file,setProgress);assign(sid,a);}
  const mayLeave=()=>!dirty||window.confirm('Hay cambios sin guardar. ¿Descartarlos?');
  return <div className="videolab"><header><div><h1>VideoLab</h1><p>Elegí un Guion, completá las escenas y creá tu video.</p></div><button disabled={busy} onClick={()=>void task(reload)}>Actualizar</button></header>
    {error&&<p role="alert" className="vl-error">{error}</p>}{notice&&<p role="status">{notice}</p>}{busy&&<p role="status">Procesando… {progress>0?`${Math.round(progress*100)}% subido — validando archivo`:''}</p>}
    <fieldset disabled={busy}>
    <div className="vl-toolbar"><button onClick={()=>{if(mayLeave()){setProject(null);setDirty(false);}}}>Nuevo video</button><select aria-label="Abrir proyecto" value={project?.id||''} onChange={e=>{if(e.target.value&&mayLeave())void task(()=>open(e.target.value));}}><option value="">Continuar un proyecto…</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select>
      <button onClick={()=>{setAdmin({id:'',nombre:'',descripcion:'',objetivo:'',escenas:[],musica_sugerida:'',activo:true});setSceneJson('[]');}}>Administrar / crear Guion</button></div>
    {!project&&<section><h2>Elegí un Guion</h2>{!guiones.some(g=>g.activo)&&<p>No hay Guiones activos disponibles. Revisá la tabla y los permisos de Supabase.</p>}<div className="vl-grid">{guiones.map(g=><article key={g.id}><h3>{g.nombre}{!g.activo?' (inactivo)':''}</h3><p>{g.descripcion}</p><p>{g.objetivo}</p><p>Música sugerida: {g.musica_sugerida||'Sin indicación'}</p>{g.activo&&<button onClick={()=>void task(async()=>{const p=await api<Project>('/projects','POST',fromGuion(g));setProject(p);setAssets([]);setDirty(false);setProjects(await api('/projects'));})}>Usar Guion</button>}<button onClick={()=>{setAdmin(g);setSceneJson(JSON.stringify(g.escenas,null,2));}}>Editar Guion</button></article>)}</div></section>}
    {admin&&<section className="vl-admin"><h2>{admin.id?'Editar':'Crear'} Guion</h2><p>Los cambios afectan videos nuevos. Los proyectos existentes conservan sus escenas.</p>{(['nombre','descripcion','objetivo','musica_sugerida'] as const).map(key=><label key={key}>{key}<input value={admin[key]||''} onChange={e=>setAdmin({...admin,[key]:e.target.value})}/></label>)}<label><input type="checkbox" checked={admin.activo} onChange={e=>setAdmin({...admin,activo:e.target.checked})}/>Activo</label><label>Escenas (JSON: nombre, tipo, duracion_sugerida en segundos, instruccion_comercial)<textarea rows={8} value={sceneJson} onChange={e=>setSceneJson(e.target.value)}/></label><button onClick={()=>void task(async()=>{const value={...admin,escenas:JSON.parse(sceneJson)};fromGuion(value);const {id,...record}=value;const result=id?await supabase.from('videolab_guiones').update(record).eq('id',id).select('id'):await supabase.from('videolab_guiones').insert(record).select('id');if(result.error)throw result.error;if(!result.data?.length)throw new Error('Supabase no confirmó la escritura. Revisá los permisos.');setAdmin(null);await loadGuiones();})}>Guardar Guion</button><button onClick={()=>setAdmin(null)}>Cerrar</button></section>}
    {project&&<><div className="vl-toolbar"><label>Nombre<input value={project.name} onChange={e=>edit({...project,name:e.target.value})}/></label><label>Formato<select value={project.format} onChange={e=>edit({...project,format:e.target.value as Project['format']})}>{['9:16','4:5','1:1','16:9'].map(f=><option key={f}>{f}</option>)}</select></label><span>{(duration(project)/30).toFixed(1)} / 60 s</span><button onClick={()=>void task(async()=>{await save();setNotice('Proyecto guardado');})}>{dirty?'Guardar cambios':'Guardar proyecto'}</button></div>
    <div className="vl-layout"><section><h2>Completá las escenas</h2><label><input type="checkbox" checked={project.muteAll} onChange={e=>edit({...project,muteAll:e.target.checked})}/>Silenciar audio de todos los videos</label>
    {project.scenes.map((s,i)=>{const a=assets.find(a=>a.id===s.assetId);return <article key={s.id} draggable onDragStart={()=>setDrag(i)} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(drag!==null)reorder(drag,i);setDrag(null);}}>
      <div className="vl-toolbar"><strong>{i+1}. {s.name}</strong><span>{s.type}</span><button disabled={i===0} onClick={()=>reorder(i,i-1)}>↑</button><button disabled={i===project.scenes.length-1} onClick={()=>reorder(i,i+1)}>↓</button><button onClick={()=>{const scenes=[...project.scenes];scenes.splice(i+1,0,{...s,id:crypto.randomUUID(),transition:'cut',overlap:0});edit({...project,scenes});}}>Duplicar</button><button disabled={project.scenes.length===1} onClick={()=>{const scenes=project.scenes.filter(x=>x.id!==s.id);scenes[scenes.length-1]={...scenes.at(-1)!,transition:'cut',overlap:0};edit({...project,scenes});}}>Eliminar</button></div>
      <p>{s.instruction}</p><p className="text-sm">Duración sugerida: {((s.suggestedFrames??s.frames)/30).toFixed(1)} s</p><label>Nombre de escena<input value={s.name} onChange={e=>updateScene(s.id,{name:e.target.value})}/></label>
      <div className="vl-toolbar"><label className="vl-file">Desde PC<input type="file" accept={visualTypes.join(',')} onChange={e=>{const f=e.target.files?.[0];if(f)void task(()=>importLocal(s.id,f));e.target.value='';}}/></label><button onClick={()=>setPicker(s.id)}>Desde Transferencias</button></div><p>{a?.name||'Colocá una foto o video'}</p>
      <div className="vl-fields"><Numeric label="Duración (s)" value={s.frames/30} min={1/30} onChange={n=>updateScene(s.id,{frames:Math.round(n*30)})}/>{a?.kind==='video'&&<><Numeric label="Recortar desde (s)" value={s.inFrame/30} max={3600} step={.1} onChange={n=>updateScene(s.id,{inFrame:Math.round(n*30)})}/><span>Fin: {((s.inFrame+s.frames)/30).toFixed(2)} s</span><label><input type="checkbox" checked={s.muted} onChange={e=>updateScene(s.id,{muted:e.target.checked})}/>Silenciar video</label><Numeric label="Volumen original" value={s.volume} max={1} step={.1} onChange={n=>updateScene(s.id,{volume:n})}/></>}
      <label>Encuadre<select value={s.fit} onChange={e=>updateScene(s.id,{fit:e.target.value as Scene['fit']})}><option value="contain">Ajustar</option><option value="cover">Rellenar</option></select></label>{(['x','y'] as const).map(axis=><label key={axis}>Posición {axis.toUpperCase()}<input type="range" min="0" max="1" step=".01" value={s[axis]} onChange={e=>updateScene(s.id,{[axis]:Number(e.target.value)})}/></label>)}
      {i<project.scenes.length-1&&<><label>Unión siguiente<select value={s.transition} onChange={e=>updateScene(s.id,{transition:e.target.value as Scene['transition'],overlap:e.target.value==='cut'?0:15})}><option value="cut">Corte</option><option value="dissolve">Fundido cruzado</option></select></label>{s.transition==='dissolve'&&<Numeric label="Fundido (s)" value={s.overlap/30} min={1/30} max={2} step={.1} onChange={n=>updateScene(s.id,{overlap:Math.round(n*30)})}/>}</>}
      </div></article>;})}<button onClick={()=>edit({...project,scenes:[...project.scenes,scene()]})}>Agregar escena</button></section><Preview project={project} assets={assets}/></div>
      <section><h2>Música</h2><p>Biblioteca permanente. Al elegir una pista se copia al proyecto.</p><label className="vl-file">Subir música a la biblioteca<input type="file" accept=".mp3,.wav,.m4a,.ogg,.flac" onChange={e=>{const f=e.target.files?.[0];if(f)void task(async()=>{await upload('/music',f,setProgress);setMusic(await api('/music'));});e.target.value='';}}/></label>
        {music.map(a=><div className="vl-music" key={a.id}><span>{a.name}</span><audio controls preload="none" src={`/api/videolab/music/${a.id}`}/><button onClick={()=>void task(async()=>{const copy=await api<Asset>(`/projects/${project.id}/import`,'POST',{source:'music',id:a.id});setAssets(v=>[...v,copy]);const frames=Math.min(duration(project),Math.floor(copy.probe.duration*30));edit({...project,music:{assetId:copy.id,inFrame:0,frames,startFrame:0,volume:.3,fadeIn:Math.min(30,Math.floor(frames/2)),fadeOut:Math.min(30,Math.floor(frames/2))}});})}>Usar pista</button><button onClick={()=>{if(window.confirm(`¿Eliminar ${a.name} de la biblioteca? Las copias de proyectos se conservan.`))void task(async()=>{await api(`/music/${a.id}`,'DELETE');setMusic(await api('/music'));});}}>Eliminar pista</button></div>)}
        {project.music&&<><p>Pista: {assets.find(a=>a.id===project.music?.assetId)?.name}</p><div className="vl-fields">{(['inFrame','frames','startFrame','fadeIn','fadeOut'] as const).map(key=><Numeric key={key} label={{inFrame:'Recortar desde (s)',frames:'Duración (s)',startFrame:'Comienza en (s)',fadeIn:'Fade in (s)',fadeOut:'Fade out (s)'}[key]} value={project.music![key]/30} max={key==='inFrame'?3600:60} step={.1} onChange={n=>edit({...project,music:{...project.music!,[key]:Math.round(n*30)}})}/>)}<Numeric label="Volumen música" value={project.music.volume} max={1} step={.1} onChange={n=>edit({...project,music:{...project.music!,volume:n}})}/></div><button onClick={()=>edit({...project,music:undefined})}>Quitar música del proyecto</button></>}
      </section><section><h2>Renderizar</h2><p>Un trabajo a la vez. Podés seguir usando PLIP mientras se procesa.</p><button disabled={jobs.some(j=>activeStates.includes(j.state))} onClick={()=>void task(async()=>{const p=await save();await api(`/projects/${p.id}/jobs`,'POST',{});setJobs(await api(`/jobs?projectId=${p.id}`));})}>Guardar y renderizar MP4</button>
        {jobs.map(j=><article key={j.id}><strong>{labels[j.state]||j.state} — {Math.round(j.progress*100)}%</strong><p>{j.error}</p>{['queued','preparing','rendering'].includes(j.state)&&<button onClick={()=>void task(async()=>{await api(`/jobs/${j.id}/cancel`,'POST',{});})}>Cancelar</button>}{j.state==='completed'&&<><video controls preload="none" className="vl-result" src={`/api/videolab/jobs/${j.id}/output`}/><a href={`/api/videolab/jobs/${j.id}/output?download=1`}>Descargar MP4</a><button onClick={()=>void task(async()=>{await api(`/jobs/${j.id}/publish`,'POST',{});setNotice('MP4 copiado a Transferencias. El original sigue disponible aquí.');})}>Copiar a Transferencias</button></>}</article>)}</section>
    </>}
    </fieldset>
    {picker&&project&&<TransferenciasPicker accept={visualTypes} onClose={()=>setPicker(null)} onSelectReferences={async files=>{const a=await api<Asset>(`/projects/${project.id}/import`,'POST',{source:'transferencias',id:files[0].id});assign(picker,a);}}/>}
  </div>;
}
